version: '3.6'

services:
  Accept licenses:
    build:
      context: .
      dockerfile: androidDocker/Dockerfile
    container_name: set-android
    environment:
        - ANDROID_HOME = /usr/local/android-sdk
    command: yes | sdkmanager --licenses || exit 0 && yes | sdkmanager --update || exit 0
  
  
  executed-katalon:
    build:
      context: .
      dockerfile: katalonDocker/Dockerfile
    container_name: executed-katalon
    command: bash -c "cd ~/Katalon-Android && katalon-execute.sh -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_01" -browserType="Android""