version: '3.6'

services:
  set-android:
    build:
      context: .
      dockerfile: androidDocker/Dockerfile
    container_name: set-android
    command: >
        bash -c "
        yes | sdkmanager --licenses || exit 0 && yes | sdkmanager --update || exit 0
        sdkmanager 'system-images;android-21;default;armeabi-v7a' && echo 'no' | avdmanager create avd -n test -k 'system-images;android-21;default;armeabi-v7a'
        ls "

  executed-katalon:
    build:
      context: .
      dockerfile: katalonDocker/Dockerfile
    container_name: executed-katalon
    command: bash -c "cd ~/Katalon-Android && katalon-execute.sh -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_01" -browserType="Android""